Tradable/Tradable/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import home_view, about_view, myprofile_view, contact_view, help_view, blank_view, privacy_view
from django.conf import settings
from django.conf.urls.static import static
from items.views import item_list_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', about_view, name='about'),
	path('help/', help_view, name='help'),
    path('privacy/', privacy_view, name='privacy'),
	path('contact/',contact_view, name='contact'),
    path('myprofile/', myprofile_view, name='myprofile'),
    path('items/', include('items.urls')),
    path('about:blank/', blank_view, name='blank'),
    path('users/', include('users.urls')),
    path('messages/', include('chat.urls', namespace="messages")),
	path('', item_list_view , name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tradable/chat/urls.py
from django.urls import path, re_path


from chat.views import ThreadView, InboxView, MessagesView

app_name = 'chat'
urlpatterns = [
    path("", MessagesView, name='message'),
    path("inbox/", InboxView.as_view(), name='inbox'),
    re_path(r"^(?P<username>[\w.@+-]+)/(?P<itemID>\d+)", ThreadView.as_view()),
]

Tradable/chat/models.py
from django.db import models

from django.conf import settings
from django.db import models
from django.db.models import Q
from items.models import Item
from django.db.models.signals import post_save
from django.dispatch import receiver


class ThreadManager(models.Manager):
    # returns a list that contains all the chat rooms that a user has.
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    # returns a chat room that is searched or created with three fields, which are the first user, second user, and the item.
    def get_or_new(self, user, other_username, itemID):  # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username) & Q(item__id=itemID)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username) & Q(item__id=itemID)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            selectedItem = Item.objects.get(id=itemID)
            if user != user2:
                obj = self.model(
                    first=user,
                    second=user2,
                    item=selectedItem
                )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    # It saves the first user in this chat.
    first = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    # It saves the second user in this chat.
    second = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    # It saves the latest updated of this chat.
    updated = models.DateTimeField(auto_now=True)
    # It saves the created time of this chat.
    timestamp = models.DateTimeField(auto_now_add=True)
    # It saves the related item of this chat.
    item = models.ForeignKey(Item, blank=True, null=True, on_delete=models.CASCADE)
    # It saves the ThreadManager object that provides functions for other usages in view function or web socket function.
    objects = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class ChatMessage(models.Model):
    # It saves the related thread object.
    thread = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    # It saves the user that created the message, which is either first user or second user.
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    # It saves the message content.
    message = models.TextField()
    # It saves the created time of the message.
    timestamp = models.DateTimeField(auto_now_add=True)


class OfferMessage(models.Model):
    # It saves the related thread object.
    thread = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    # It saves the user that created the offer message, which is either first user or second user.
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    # It saves the money that the buyer wishes to pay.
    offer = models.DecimalField(decimal_places=2, max_digits=10000, default=None, null=True)
    # It saves whether the seller accepts or rejects the offer made by the buyer.
    offerAccept = models.BooleanField(null=True)
    # It saves the created time of the offer message.
    timestamp = models.DateTimeField(auto_now_add=True)


#If the seller accepts the offer made by the buyer, it will create a new offer message with a value of True in offerAccept. And the following function is placed in models.py in the chat app which used to change the related item availability when the seller agreed to sell it to other user.
@receiver(post_save, sender=OfferMessage)
def update_item_isSoldOut(sender, instance, **kwargs):
    if (instance.offerAccept is True):
        searchID = instance.thread.item.id
        Item.objects.filter(id=searchID).update(isSoldOut=True)

Tradable/chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control"}
        )
    )

Tradable/chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.edit import FormMixin

from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage

# There are two situations when directing to the message view page.
# The first one is by clicking the message button at the top navigation menu.
# The second one is by clicking the buy button in the item dynamic look up view.
# The first one does not need to render the thread view.
# The second one needed to render the thread view, which is related to the seller and the selected item.
# Therefore, it needs to check whether it needs to render the corresponding thread view or not.


def MessagesView(request, **kwargs):
    seller = ""
    item_id = ""
    # The item_dynamic_lookup_view will redirect the buyer to the message view, and at the same time send the corresponding data by session. Therefore, it is used to distinguish whether the thread view needs to be render or not. In the function, it used if-else to check the data is here or not.
    if ('seller' in request.session):
        seller = request.session['seller']
        del request.session['seller']
    else:
        seller = None
    if ('item_id' in request.session):
        item_id = request.session['item_id']
        del request.session['item_id']
    else:
        item_id = None
    sellerContext = {
        'seller': seller,
        'item_id': item_id
    }
    return render(request, "chat/message.html", sellerContext)


class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'
    # rendering the current chat rooms that a user has

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


# returning the thread object to the frontend and receiving the POST function from the frontend.
class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username = self.kwargs.get("username")
        itemID = self.kwargs.get("itemID")
        # find the thread object by searching with the username and the item id. If the thread object cannot be found or created, it will generate a 404 error.
        obj, created = Thread.objects.get_or_new(self.request.user, other_username, itemID)
        if obj == None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    # it process when the thread view receives a POST.
    def post(self, request, *args, **kwargs):
        # The POST is generated by the user submitting the message.
        if not request.user.is_authenticated:
            return HttpResponseForbidden()

        self.object = self.get_object()
        form = self.get_form()
        # After receiving the POST, it will check the whether it is valid or not, and then proceed to the form_valid() function
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    # it will create a new message and save it
    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

Tradable/chat/templates/chat/message.html
{% extends "base.html" %}

{% block style %}
<style>

br{
    display: none;
}

#inbox{
    position:absolute;
    top:45px;
}
#belowNav{
    diaplay: none;
}

</style>
{% endblock %}

{% block content %}

<div class="d-block d-lg-none fixed-top bg-light text-center" id="inbox" >
    <a href="{% url 'messages:message'%}" id="backToInbox" class="btn btn-secondary justify-content-center my-0 mx-auto w-100">Inbox</a>
</div>
<div class="container-fluid row  p-0 m-0 ">
    <div class="col-xl-3 col-4 p-0 border-right desktopframe" id="desktopframe">
    <br class="d-block d-lg-none">
        <iframe class="d-none d-lg-block" id="left" style="height:80vh; width:100%"  frameBorder="0" src="{% url 'messages:inbox'  %}"></iframe>
    </div>
	<div class="col p-0 ">
        {% if seller == None %}
        <br class="d-block d-lg-none">
        <iframe class="d-none d-lg-block" id="right" iframe name="right" style="height:80vh; width:100%" frameBorder="0" src="{% url 'blank'  %}">
        </iframe>
        {% else %}
        <br class="d-block d-lg-none">
        <iframe class="d-none d-lg-block" id="right" iframe name="right" style="height:80vh; width:100%" frameBorder="0" src="/../messages/{{ seller }}/{{item_id}}/"></iframe>
        {% endif %}
    </div>
</div>

<div class="container-fluid row p-0 m-0 " id="mobileframe">
        <iframe class="d-block d-lg-none mt-4" id="right" iframe name="right" style="height:80vh; width:100%" class="border-right" frameBorder="0" src="{% url 'messages:inbox'  %}"></iframe>
</div>


{% endblock %}

{% block script %}
<script>
console.log('{{seller}}')

$('iframe#right').on('load', function() {

    var iframeWin = this.contentWindow;
    var iframeBody = this.contentDocument.body;
    //console.log(iframeWin.loc)
    // access global JS vars defined in the iframe:
    //var someIframeVariable = iframeWin.globalIframeVariable;

    // or, directly access elements in the iframe:
    var formData = $(iframeBody).find('#form');
    var msgInput = $(iframeBody).find('#id_message');
    formData.submit(function(event){
        //prevent your fomr to submit by default
        event.preventDefault()
        var msgText = msgInput.val()
        //chatHolder.append("<li>" + msgText + " via " + me + "</li>")
        //var formDataSerialized = formData.serialize()
        var finalData = {
            'message':msgText
        }
        var itemID = iframeWin.location.pathname.replace(/[^0-9]/g,'')
        var firstRemove = iframeWin.location.pathname.replace('/messages/', '')
        var secondRemove = firstRemove.replace(itemID.toString(), '')
        var seller = secondRemove.replace("//", '')


    })
});

</script>
{% endblock %}

Tradable/chat/templates/chat/thread.html
{% load crispy_forms_tags %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Material Design for Bootstrap fonts and icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons">

		<!-- icon pack -->
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <!-- Material Design for Bootstrap CSS -->
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script|Righteous|Roboto+Mono|Gafata|Open+Sans" rel="stylesheet">
		<title>messages</title>

	<style>

		body::-webkit-scrollbar {
			width: 0.5em;
			display:none;
		}


		*{
				font-family: 'Open Sans', sans-serif;
				font-size: 18px;
    }

    *, *:before, *:after {
        box-sizing: border-box;
    }

    body{

			background: whitesmoke;
    }

		#receive{
				background-color: white;
				padding: 6px 12px 7px;
		}
		#send{
				background-color: #DAF7A6;
				padding: 6px 12px 7px;
		}

		#backToInbox{
				width:100%;
		}

		#send > .list-group-item:first-child {
    	border-top-left-radius: 0em;
		}

		.list-group-item:first-child {
			/*overwrite bootstrap default first table element style*/
    	border-top-left-radius: 1.3em;
    	border-top-right-radius: 1.3em;
		}

		.list-group-item:last-child {
			border-bottom-right-radius: 1.3em;
			border-bottom-left-radius: 1.3em;
		}

		li {
				word-break: break-all;
				font-size:17px;
				border-radius: 1.3em;
				max-width:40%;
		}

		#chatinput{
				border: 2px;
				border-radius: 10px;

				margin: 10px;
		}

		#submit{
				position:absolute;
				bottom: 10px;
				right: 10px;
				background-color: white ;
		}
		p{
			margin: 5px;
		}
    </style>
  </head>
  <body>
	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
	<script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>
	<script>$(document).ready(function() { $('body').bootstrapMaterialDesign(); });</script>


	<br>

	<div class="fixed-top d-inline-flex align-items-center justify-content-center p-1 border bg-light">
		<img src="{{ object.item.displayPhoto.url }}" class="icon img-thumbnail rounded-circle p-0" style="width:3rem; height:3rem;">
		<h4 class="text-left py-auto pl-2">{{object.item.name}}</h4>
		<h4  class="py-auto">&nbsp;from: {% if user != object.first %}{{ object.first }}{% else %}{{ object.second }}{% endif %}</h4>
	</div>
	<br>
	<br>
	<div class="conatainer-fluid row" style="width:100%">
		<div class="col container pl-4">

			<ul class="row list-group p-0" id='chat-items'>

				{% for chat in object.chatmessage_set.all %}
				{% if chat.user == user %}
				<li id='send'class="m-1 list-group-item border ml-auto">{{ chat.message }}</li>
				{% else %}
				<li id='receive' class="m-1 list-group-item border mr-auto ">{{ chat.message }}</li>
				{% endif %}

				{% endfor %}
			</ul>

			<br>
			<br>
			<br>
			<br>
			<br>
			<br>
			<div class="fixed-bottom bg-light">
				<div class="d-flex" style="" id="sellandbuy">
					<div class='col'>
						<h4 class='' id='offerPriceHolder'></h4>
						<h4 class='' id='offerAcceptHolder'></h4>
					</div>
					<div id="offerinputBox">
					<div class='d-inline-flex'>
					{% if user != object.item.seller %}
						<p class='mb-0 pt-1' id='buyerOfferTitle'>Enter Your Offer:</p>
						<span class="bmd-form-group pr-1 p-0">
							<input class="form-control" type="number" class="" id="offersubmit">
						</span>
						<button class="btn btn-raised btn-secondary" type='button' id='sendOfferButton'>Send</button>
					{% else %}
						<button class="btn btn-raised btn-secondary mr-2" type='button' id='acceptButton'>Accept</button>
						<button class="btn btn-raised btn-secondary" type='button' id='rejectButton'>Reject</button>
					{% endif %}
					</div>
					</div>
				</div>
				<div class="pl-3 p-1 m-1 bg-white" id="chatinput">
					<form class="m-0" id='form' method='POST'> {% csrf_token %}
						<input type='hidden' id='myUsername' value='{{ user.username }}'>
						{{form.as_p }}
						<input onclick="" type='submit' class='btn btn-secondary' id="submit">
					</form>
				</div>
			</div>

		</div>
	</div>

	<script src='https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.js'>
	</script>
	<script>

	var removeMsgLabel = function(){
		$('label').remove();
	}

	var scDown = function(){
			$(document).scrollTop($(document).height());
	}

	$(function(){
		scDown();
		removeMsgLabel();
	})

	// websocket scripts
	//console.log(window.location)
	var loc = window.location
	//<form id='form'>
	var formData = $("#form")
	var offerInput = $('#offersubmit')
	//django name that message with an id=id_message
	var msgInput = $('#id_message')
	var chatHolder = $("#chat-items")
	var offerPriceHolder = $('#offerPriceHolder')
	var buyerOfferTitle = $('#buyerOfferTitle')
	var sendOfferButton = $('#sendOfferButton')
	var acceptButton = $('#acceptButton')
	var rejectButton = $('#rejectButton')
	var offerAcceptHolder = $('#offerAcceptHolder')
	var offerinputBox = $('#offerinputBox')
	var me = $("#myUsername").val()

	var offerReject = false

	var wsStart = 'ws://'
	if (loc.protocol == 'https:'){
		wsStart = 'wss://'
	}
	var endpoint = wsStart + loc.host + loc.pathname
	var socket = new ReconnectingWebSocket(endpoint)

	socket.onmessage = function(e){
		console.log("message", e)
		var chatDataMsg = JSON.parse(e.data)
		if (chatDataMsg.hasOwnProperty('message')){
	        if (chatDataMsg.username === me){
				chatHolder.append("<li id='send'class='m-1 list-group-item border ml-auto'>" + chatDataMsg.message + "</li>")
        	}
        	else{
				chatHolder.append("<li id='receive' class='m-1 list-group-item border mr-auto'>" + chatDataMsg.message + "</li>")
        	}
			scDown();
    	}

     	if (chatDataMsg.hasOwnProperty('offermessage')){
     		var displayPrice = "Offered price: HK$ " + chatDataMsg.offermessage.toString()
     		offerPriceHolder.text(displayPrice)
     		buyerOfferTitle.text("Update Your Offer:")
     		console.log(displayPrice)
     		if (offerReject){
     			offerAcceptHolder.text("")
     			offerReject = false
     		}
     	}

     	if (chatDataMsg.hasOwnProperty('offerAccept')){
     		if (chatDataMsg.offerAccept === true){
     			offerAcceptHolder.text("Accepted")
     			offerinputBox.hide()
     		}else if (chatDataMsg.offerAccept === false){
     			offerReject = true
     			offerAcceptHolder.text("Rejected")
     		}
     	}
		scDown();
	}
	socket.onopen= function(e){
		console.log("open", e)
		formData.submit(function(event){
			//prevent your fomr to submit by default
			event.preventDefault()
			var msgText = msgInput.val()
			//chatHolder.append("<li>" + msgText + " via " + me + "</li>")
			//var formDataSerialized = formData.serialize()
			var finalData = {
				'message':msgText
			}
			socket.send(JSON.stringify(finalData))
			//socket.send(formDataSerialized)
			//msgInput.val('')
			formData[0].reset()
		})

		sendOfferButton.click(function(event){
			event.preventDefault()
			var offer = offerInput.val()
			offerWithDecimal = Number.parseFloat(offer).toFixed(2)
			var offerData = {
				'offermessage':offerWithDecimal
			}
			socket.send(JSON.stringify(offerData))
     		offerInput.val(null)

     		if (offerReject){
     			offerAcceptHolder.text("")
     			offerReject = false
     		}
		})

		acceptButton.click(function(event){
			event.preventDefault()
			var offerData = {
				'offerAccept':true
			}
			//console.log(offerData.offerAccept)
			socket.send(JSON.stringify(offerData))
		})

		rejectButton.click(function(event){
			event.preventDefault()
			var offerData = {
				'offerAccept':false
			}
			//console.log(offerData.offerAccept)
			socket.send(JSON.stringify(offerData))
		})
	}

	socket.onerror= function(e){
		console.log("error", e)
	}
	socket.onclose= function(e){
		console.log("close", e)
	}

	</script>
	</body>
</html>