Tradable/Tradable/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import home_view, about_view, myprofile_view, contact_view, help_view, blank_view, privacy_view
from django.conf import settings
from django.conf.urls.static import static
from items.views import item_list_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', about_view, name='about'),
	path('help/', help_view, name='help'),
    path('privacy/', privacy_view, name='privacy'),
	path('contact/',contact_view, name='contact'),
    path('myprofile/', myprofile_view, name='myprofile'),
    path('items/', include('items.urls')),
    path('about:blank/', blank_view, name='blank'),
    path('users/', include('users.urls')),
    path('messages/', include('chat.urls', namespace="messages")),
	path('', item_list_view , name='home'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Tradable/chat/urls.py
from django.urls import path, re_path


from chat.views import ThreadView, InboxView, MessagesView

app_name = 'chat'
urlpatterns = [
    path("", MessagesView, name='message'),
    path("inbox/", InboxView.as_view(), name='inbox'),
    re_path(r"^(?P<username>[\w.@+-]+)/(?P<itemID>\d+)", ThreadView.as_view()),
]

Tradable/items/urls.py
from django.urls import path
from items.views import item_list_view, item_create_view, item_dynamic_lookup_view, item_base_view, my_item_view, edit_item_view

urlpatterns = [

    path('create/', item_create_view, name='createitem'),
    path('<int:item_id>/', item_dynamic_lookup_view, name='lookupitem'),
    path('myitem/', my_item_view, name='myitem'),
    path('edit/<int:item_id>/', edit_item_view, name='edititem'),
]

Tradable/items/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from PIL import Image

# Create your models here.
# Item model to store all uploaded item from user


class Item(models.Model):
    # It saves the name of the product or the post.
    name = models.CharField(max_length=100, default=None, null=False)
    # It saves the description submitted by the seller. To let other users to understand what the product is.
    description = models.TextField(default=None, null=False)
    # It saves the price of the product set by the seller.
    price = models.DecimalField(decimal_places=2, max_digits=10000, default=None, null=False)
    # It saves the condition description of the product.
    condition = models.TextField(default=None, null=False)
    # It saves the time that the item is created.
    createdDateTime = models.DateTimeField(default=timezone.now)
    # It saves the seller as a user object.
    # if the sellor account is deleted, the item posts will be deleted
    seller = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    # It saves the photo which is used to display when it is showed in the item_list_view.
    displayPhoto = models.ImageField(upload_to='item_pics', blank=False, null=True)
    # It saves the availability of the product which means that whether it is already sold or not.
    isSoldOut = models.BooleanField(default=False)

    # QuerySet will show [<Item: <seller> <name> >]
    def __str__(self):
        return f'{self.seller} {self.name}'

    # overwrite the save method
    def save(self, **kwargs):
        super().save()

        img = Image.open(self.displayPhoto.path)
        # resize profile image
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.displayPhoto.path)


class DescriptionPhoto(models.Model):
    # It saves the corresponding item to this description photo object.
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    # It saves the photo submitted by the seller.
    photo = models.ImageField(upload_to='item_pics', blank=True, null=True)

    def __str__(self):
        return f'{self.item.seller} {self.item.name}'

        # overwrite the save method
    def save(self, **kwargs):
        super().save()

        img = Image.open(self.photo.path)
        # resize profile image
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.photo.path)

Tradable/items/forms.py
from django import forms
from .models import Item


class ItemCreateForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'name',
            'description',
            'price',
            'condition',
            'displayPhoto'
        ]


class ItemEditForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'name',
            'description',
            'price',
            'condition',
            'displayPhoto'
        ]

Tradable/items/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .models import Item, DescriptionPhoto
from .forms import ItemCreateForm, ItemEditForm
from django.forms import modelformset_factory
from users.models import Profile
from django.db.models import Q


def item_base_view(request, *args, **kwargs):
    return render(request, "item/base.html", {})

# Create your views here.
# item_dynamic_lookup_view render item page for sepcific item

# It renders the specific item that is selected by users (registered users or non-registered users).
def item_dynamic_lookup_view(request, item_id, *args, **kwargs):
    # searches the selected item by the item id from the url “items/<int:item_id>/”. If the item is in the database, it gets it out. Otherwise, it will generate a 404 error
    obj = get_object_or_404(Item, id=item_id)
    photo = DescriptionPhoto.objects.select_related().filter(item=item_id)
    context = {
        "object": obj,
        "photo": photo
    }
    if (request.method == 'POST'):
        # When it gets a POST with an id “seller”, it redirects the website to the message page
        if (request.POST.get("seller")):
            # the registered user can buy the item and use the message function, it is needed to validate the user is already login or not
            if (request.user.is_authenticated):
                if (request.user != obj.seller):
                    request.session['seller'] = f'{obj.seller}'
                    request.session['item_id'] = f'{obj.id}'
                    return redirect("/messages/")
                else:
                    messages.warning(request, "This item belongs to you!")
                    return render(request, "item/lookup.html", context)
            else:
                return redirect(f'/users/login/?next=/items/{obj.id}/')
        # When it gets a POST with an id “back”, it redirects the website to the home page.
        elif (request.POST.get("back")):
            return redirect('home')

    return render(request, "item/lookup.html", context)

# item_list_all_view render a page listing all item


def item_list_view(request):

    items = Item.objects.filter(isSoldOut=False) #check if item is sold
    search_term = ''

    #sort according to create time and price
    if 'recent' in request.GET:
        # directly get the sorted query set from database
        items = items.order_by('createdDateTime')
        items = items.reverse()
    if 'low' in request.GET:
        # directly get the sorted query set from database
        items = items.order_by('price')
    if 'high' in request.GET:
        # directly get the sorted query set from database
        items = items.order_by('price')
        items = items.reverse()

    #use get method to retrieve the user desired string
    if 'search' in request.GET:
        search_term = request.GET['search']
        # directly get the sorted query set from database
        qlookup = Q(name__icontains=search_term) | Q(price__icontains=search_term) | Q(seller__username__icontains=search_term)
        items = items.filter(qlookup)
        
    paginator = Paginator(items, 15)  # show 15 items per page

    page = request.GET.get('page')
    items = paginator.get_page(page)

    get_dict_copy = request.GET.copy()
    params = get_dict_copy.pop('page', True) and get_dict_copy.urlencode()
    search_string = ''

    context = {'items': items, 'params': params, 'search_term': search_term}

    return render(request, "item/list_item.html", context)

#  item_create_view  remder a page to create item
#  you may also look at .forms.py

# It lets the registered user to create an item. In this view function
@login_required
def item_create_view(request):
    # The formset saves the description photos which is limited at 4 photos at maximum.
    descriptionPhotoFormset = modelformset_factory(DescriptionPhoto, fields=('photo',), extra=4)
    if request.method == 'POST':
        form = ItemCreateForm(request.POST or None, request.FILES or None)
        formset = descriptionPhotoFormset(request.POST or None, request.FILES or None)
        # they are valid by the model preset validation function. If they are passed, the form will be saved without other process. The formset will be extract out and saved one by one
        if form.is_valid() and formset.is_valid():
            createItem = form.save()
            createItem.seller = request.user
            createItem.save()
            for f in formset:
                try:
                    descriptionPhoto = DescriptionPhoto(item=createItem, photo=f.cleaned_data['photo'])
                    descriptionPhoto.save()
                except Exception as e:
                    break
            # redirect back to the home with a success notification.
            messages.success(request, f'You created a new item')
            return redirect('home')

    else:
        form = ItemCreateForm()
        formset = descriptionPhotoFormset(queryset=DescriptionPhoto.objects.none())

    context = {
        'form': form,
        'formset': formset,
    }

    return render(request, "item/create.html", context)


@login_required
def my_item_view(request):
    items = Item.objects.filter(seller=request.user)
    search_term = ''

    if 'recent' in request.GET:
        items = items.order_by('createdDateTime')
        items = items.reverse()

    if 'low' in request.GET:
        items = items.order_by('price')

    if 'high' in request.GET:
        items = items.order_by('price')
        items = items.reverse()

    if 'search' in request.GET:
        search_term = request.GET['search']
        items = items.filter(name__icontains=search_term)

    paginator = Paginator(items, 15)  # show 15 items per page

    page = request.GET.get('page')  # GET method to retrieve user selected page
    items = paginator.get_page(page)  #display the item list of specific page

    get_dict_copy = request.GET.copy()
    params = get_dict_copy.pop('page', True) and get_dict_copy.urlencode()
    search_string = ''

    context = {'items': items, 'params': params, 'search_term': search_term}

    if (request.method == 'POST'):
        if (request.POST.get('delete')):
            item_id = request.POST.get('delete')
            deleteItem = Item.objects.get(id=item_id)
            deleteItem.delete()

            messages.success(request, f'You deleted your item')
            return render(request, "item/myitem.html", context)

    return render(request, "item/myitem.html", context)

# it provides editing function for the seller to change the data of the item and the description photos
@login_required
def edit_item_view(request, item_id):
    # searches the item from the database. If it cannot be found, 404 error will be generated.
    item = get_object_or_404(Item, id=item_id)

    if (item != None):
        itemForm = ItemEditForm(instance=item)
        images = DescriptionPhoto.objects.filter(item__id=item.id)
        descriptionPhotoFormset = modelformset_factory(DescriptionPhoto, fields=('photo',), extra=0)
        newDescriptionPhotoFormset = modelformset_factory(DescriptionPhoto, fields=('photo',), extra=4 - images.count())
        formset = descriptionPhotoFormset(queryset=images, prefix='old')
        newformset = newDescriptionPhotoFormset(queryset=DescriptionPhoto.objects.none(), prefix='new')
        if (request.method == 'POST'):
            if (request.POST.get('save')):
                itemForm = ItemEditForm(request.POST, request.FILES, instance=item)
                formset = descriptionPhotoFormset(request.POST or None, request.FILES or None, queryset=images, prefix='old')
                newformset = newDescriptionPhotoFormset(request.POST or None, request.FILES or None, prefix='new')
                if (itemForm.is_valid() and formset.is_valid() and newformset.is_valid()):
                    # deleting the previous description photos first and save the new description photos.
                    itemForm.save()
                    deleteList = []
                    i = 0
                    for f in formset:
                        try:
                            cd = f.cleaned_data
                            if(cd.get('photo') is False):
                                deleteList.append(i)
                            else:
                                f.save()
                            i = i + 1
                        except Exception as e:
                            break
                    for f in newformset:
                        try:
                            newItemPhoto = DescriptionPhoto(item=item, photo=f.cleaned_data['photo'])
                            newItemPhoto.save()
                        except Exception as e:
                            continue
                    for i in deleteList:
                        images[i].delete()
                    messages.success(request, f'You have edited your item!')
                    return redirect('myitem')
            else:
                return redirect('myitem')

        if (item.seller == request.user):
            photo = DescriptionPhoto.objects.select_related().filter(item=item_id)
            context = {
                'item': item,
                'photo': photo,
                'itemForm': itemForm,
                'formset': formset,
                'newformset': newformset
            }
            return render(request, "item/edit_item.html", context)
        else:
            messages.warning(request, f"There are something wrong!")
            return redirect('home')

Tradable/items/templates/item/base.html
{% extends 'base.html' %}

<!--item base.html on top of root base.html -->
{% block content %}
<div class = "container-fluid p-0">

<div class="row m-0">

	<div class = "container-fluid col-xl-10 col-lg-11 col-md-12">
		<div style="position:absolute; left:20px ; top: -35px;">
			<form class="row m-0 ">
			<!--search bar-->
				<div class="col-11 mx-auto mb-2">
					<span class="bmd-form-group ">
						<label for="search" class="bmd-label-floating ">Search</label>
						<input id="search" type="text" class="form-control" style="padding-top:35px"; name="search">
					</span>
				</div>
			</form>
		</div>
		<div style="height:35px"></div>
		<div class="row container-fluid">
			<div class="dropdown pt-1">
				<button type="button" class="btn btn-secondary dropdown-toggle ml-2 mb-0" id="dropdownMenuOffset" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-offset="0,0">
				sort
				</button>
				
				<!--sorting dropdown menu-->
				<div class="dropdown-menu" aria-labelledby="dropdownMenuOffset">
					<a class="dropdown-item" href="?recent=True&search={{search_term}}">Most recent</a>
					<a class="dropdown-item" href="?low=True&search={{search_term}}">Price-low to high</a>
					<a class="dropdown-item" href="?high=True&search={{search_term}}">Price-high to low</a>
				</div>
			</div>	
			
			<div class="ml-auto">
			<!--functional button group-->
				{% if user.is_authenticated %}
					<a class="justify-content-end" href="{% url 'myitem' %}"><button class="btn btn-raised btn-secondary px-2" type= 'button'>My item</button></a>
					<a class="justify-content-end" href="{% url "createitem" %}"><button class="btn btn-raised btn-secondary px-2" type= 'button'>Create an item</button></a>
				{% else %}
					<a class="justify-content-end" href="{% url "login" %}"><button class="btn btn-raised btn-secondary" type= 'button' >login to create</button></a>
				{% endif %}
			</div>

		</div>


		{% block myitem%}
		{% endblock%}
		{% block item %}
		<!---->
		{% endblock %}
	</div>

</div>
<div class= "container mt-2" >
<!--pagination-->
<!--django build in app-->
	<nav aria-label="Page navigation">
		<ul class="pagination justify-content-center">
			{% if items.has_previous %}
				<li class="page-item"><a class="page-link" href="?page=1&{{params}}">&laquo; first</a></li>
				<li class="page-item"><a class="page-link" href="?page={{ items.previous_page_number }}&{{params}}">previous</a></li>
			{% endif %}

			{% for item in items.paginator.page_range %}
			<li class="page-item"><a class="page-link" href="?page={{ item }}&{{params}}">{{ item }}</a></li>
			{% endfor %}

			{% if items.has_next %}
				<li class="page-item"><a class="page-link" href="?page={{ items.next_page_number }}&{{params}}">next</a></li>
				<li class="page-item"><a class="page-link" href="?page={{ items.paginator.num_pages }}&{{params}}">last &raquo;</a></li>
			{% endif %}
		</ul>
	</nav>
</div>
</div>
{% endblock %}

Tradable/items/templates/item/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block style%}
<style>

.upload{
    border:0;
    color: gray;
    background-color:transparent;
    font-size: 1.2rem;
}

.upload-wrapper {
  position: relative;
  display: inline-block;
  height: auto;
}

.upload-wrapper input[type=file] {
  font-size: 1rem;
  position: absolute;
  left: 0;
  top: 0;
  opacity: 0;
}

</style>
{% endblock %}

{% block content %}

<div class="container">
	<h3>Create new item here</h3>
	<form method='POST' enctype='multipart/form-data'> {% csrf_token %}
		{{ form.name|as_crispy_field }}
		{{ form.description|as_crispy_field  }}
		{{ form.price|as_crispy_field  }}
		{{ form.condition|as_crispy_field  }}
        <div>
		<!--below are customized upload photo button-->
		<div id="div_id_displayPhoto" class="form-group">
				<div class="upload-wrapper">
					<button class="upload">*Select a display picture</button> 
					<input type="file" name="displayPhoto" accept="image/*" class="clearablefileinput" required="" id="id_displayPhoto">
					<p style="font-size:0.5em;">no file selected</p>
				</div>
			</div>
			<input type="hidden" name="form-TOTAL_FORMS" value="4" id="id_form-TOTAL_FORMS">
			<input type="hidden" name="form-INITIAL_FORMS" value="0" id="id_form-INITIAL_FORMS">
			<input type="hidden" name="form-MIN_NUM_FORMS" value="0" id="id_form-MIN_NUM_FORMS">
			<input type="hidden" name="form-MAX_NUM_FORMS" value="1000" id="id_form-MAX_NUM_FORMS">
			<div class="multiField">
				<div id="div_id_form-0-photo" class="form-group">
						<div class="upload-wrapper">
							<button class="upload">Select a picture</button> 
							<input type="file" name="form-0-photo" accept="image/*" class="clearablefileinput" id="id_form-0-photo">
							<p style="font-size:0.5em;">no file selected</p>
						</div>
					</div>
					<input type="hidden" name="form-0-id" id="id_form-0-id">
				</div>
				<div class="multiField">
					<div id="div_id_form-1-photo" class="form-group">
						<div class="upload-wrapper">
							<button class="upload">Select a picture</button> 
							<input type="file" name="form-1-photo" accept="image/*" class="clearablefileinput" id="id_form-1-photo">
							<p style="font-size:0.5em;">no file selected</p>
						</div>
					</div>
					<input type="hidden" name="form-1-id" id="id_form-1-id">
				</div>
				<div class="multiField">
					<div id="div_id_form-2-photo" class="form-group">
						<div class="upload-wrapper">
							<button class="upload">Select a picture</button> 
							<input type="file" name="form-2-photo" accept="image/*" class="clearablefileinput" id="id_form-2-photo">
							<p style="font-size:0.5em;">no file selected</p>
						</div>
					</div>
					<input type="hidden" name="form-2-id" id="id_form-2-id">
				</div>
				<div class="multiField">
					<div id="div_id_form-3-photo" class="form-group">
						<div class="upload-wrapper">
							<button class="upload" onclick="show_selected()">Select a picture</button> 
							<input type="file" name="form-3-photo" accept="image/*" class="clearablefileinput" id="id_form-3-photo">
							<p style="font-size:0.5em;">no file selected</p>
						</div>
					</div>
					<input type="hidden" name="form-3-id" id="id_form-3-id">
				</div>
			</div>

		<input class="btn btn-raised btn-secondary" type= 'submit' value='Save'/>
		<button class="btn btn-raised btn-secondary" onclick="goBack()">Cancel</button>
	</form>
</div>

<script>
function goBack() {
    window.history.back();
}


$( document ).ready(function() {
	//change the selected file statment while file is selected
	$('input[type="file"]').change(function(e){
		var fileName = e.target.files[0].name;
	
		$(e.target).next().replaceWith('<p style="font-size:0.5em;">' + fileName +  ' has been selected</p>');
		('The file "' + fileName +  '" has been selected.');
	});
});
</script>

{% endblock %}

Tradable/items/templates/item/edit_item.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

{% block style %}
<style>
.carousel-inner > .carousel-item > img{
    margin:auto;
}
.carousel-control-prev-icon,
.carousel-control-next-icon {
  height: 100px;
  width: 100px;
  outline: black;
  background-size: 100%, 100%;
  background-image: none;
}

.carousel-control-next-icon:after
{
    font-family: 'Righteous', cursive; /* next photo */
    content: '>';
    font-size: 55px;
    color: DimGray  ;
}

.carousel-control-prev-icon:after {
    font-family: 'Righteous', cursive; /* previous photo */
    content: '<';
    font-size: 55px;
    color: DimGray ;
}

.carousel-indicators li {
    background-color: DimGray ;
}

.carousel-indicators .active {
    background-color: IndianRed    ;
}

ul {
list-style-type: none;
}

.item-icon {
    margin-top:0.3rem;
}
.card{
    max-height: 50vh;
}
ul{
    max-height: 30vh;
}
</style>
{% endblock %}

<!--do not allow edit if item is sold and display its detail-->
{% if item.isSoldOut == True %}
<div class="row container mx-auto justify-content-center" id="parents" style="overflow:hidden;">
    <div class="card bg-light border-secondary col-lg-4 col-md-5 col-10 p-0 m-3 mx-3">
        <div class="card-body p-0 m-0 ">
            <div class="container-fluid d-flex d-inline-flex mt-2 mb-3">
                <img src="{{ item.seller.profile.image.url }}" class="icon img-thumbnail rounded-circle p-0 " style="width:3rem; height:3rem;">
                <p id="sellername" class="card-text ml-1 pl-1 my-auto col-xl-8 col-7" style="font-size: 1.2rem;" >{{ item.seller }}</p>
            </div>
            <div id="photoslideshow" class="carousel slide w-100 p-0 d-flex align-items-center bg-light my-auto " style="overflow:hidden;" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#photoslideshow" data-slide-to="0" class="active"></li>
                    {% for pic in photo.all%}
                    <li data-target="#photoslideshow" data-slide-to="{{forloop.counter}}"></li>
                    {% endfor %}

                </ol>
                <div class="carousel-inner "style="overflow:hidden;" >
                    <div class="carousel-item active ">
                        <img src="{{ item.displayPhoto.url }}" class="carousel-image d-block w-100 " alt="Image Not Found">
                    </div>
                    {% for pic in photo.all %}
                        <div class="carousel-item">
                            <img src="{{ pic.photo.url }}" class="carousel-image  d-block w-100 " alt="Image Not Found">
                        </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" href="#photoslideshow" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#photoslideshow" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>

        </div>
    </div>

    <!--item detail-->
    <div class="card bg-light border-secondary col-lg-4 col-md-5 col-10 p-0 mt-md-3 mt-2 mb-3 mx-3">
        <div clas="card-body">
            <h3 class="border-bottom text-left p-1">{{item.name}}</h3>
            <div class="container-fluid ">
                <ul class="pl-0" style="overflow:hidden;">
                    <li><div class="d-flex d-inline-flex"><i class="item-icon fas fa-dollar-sign px-1"></i><p class="card-text my-auto ml-1">{{ item.price }}</p></div></li>
                    <li><div class="d-flex d-inline-flex"><i class="item-icon far fa-question-circle"></i><p class="card-text my-auto ml-1">{{ item.description }}</p></div></li>
                    <li><div class="d-flex d-inline-flex"><i class="item-icon far fa-pause-circle" ></i><p class="card-text my-auto ml-1">{{item.condition}}</p></div></li>
                    <li><div class="d-flex d-inline-flex"><i class="item-icon far fa-clock "></i><p class="card-text mt-0 ml-1">{{item.createdDateTime}}</p></div></li>
                </ul>
            </div>
            <div class="col d-flex justify-content-center d-flex align-items-end">
                <form class="d-flex mb-0" action="" method="post">{% csrf_token %}
                    <button type="submit" button class="col btn btn-secondary " name="back" value="back">Return to list</button>
                    {% if item.isSoldOut != True %}
                    <button type="submit" button class="col btn btn-secondary " name="seller" value="{{ item.seller }}">BUY!</button>
                    {% else %}
                    <h4>This item is sold out!!</h4>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="container">
    <h3>Edit your item</h3>
    <form method='POST' enctype='multipart/form-data'> {% csrf_token %}
        {{ itemForm|crispy }}
        {{ formset.management_form }}
        {% for form in formset %}
            {{ form|crispy }}
        {% endfor %}
        {{ newformset.management_form }}
        {% for form in newformset %}
            {{ form|crispy }}
        {% endfor %}
        <input class="btn btn-raised btn-secondary" type= 'submit' name='save' value='save'></input>
        <button class="btn btn-raised btn-secondary" name='back' value='back' onclick="goBack()">Cancel</button>
    </form>
</div>
{% endif %}
{% endblock %}
{% block script %}
<script>
var set_carousel_height = function(){

    $('.carousel').css({
    'height': $('.carousel').width()
    })
}

var resize_image = function(){
    $('.carousel-image').each(function(){
        current =$(this);
        console.log('true');
    });



 }

$(function(){

    set_carousel_height();
    resize_image();
    console.log($('#parents').height());

    $(window).resize(function() {
        set_carousel_height();
        resize_image();
    })
})

function goBack() {
    window.history.back();
}
</script>

{% endblock %}

Tradable/items/templates/item/list_item.html
{% extends 'item/base.html' %}

{% block style%}
<style>
#textholder{
	width:100%;
	overflow: hidden;
}
#sellername{
	overflow: hidden;
	height: 2rem;
}
#info-h{
	height: 1.7rem;
	overflow: hidden;
}
#info-t{
	height: 1.2rem;
	overflow: hidden;
}
#btn-search{
	position:absolute;

}

</style>
{% endblock %}

{% block item %}


<div class="container-fluid">
		<div class="row d-flex justify-content-center ">

			{% for item in items %}
				<div id="card" class=" col-lg-2 col-md-3 col-sm-5 col-10 card border-black p-0  
				m-1" >
					<a class="text-dark " href="/items/{{item.id}}">
						<div class="rounded card-body m-0 p-0" >
							<div class="seller m-2 row" style="height:2rem;">
								<img src="{{ item.seller.profile.image.url }}" class="icon img-thumbnail rounded-circle p-0" style="width:2rem; height:2rem;">
								<p id="sellername" class="card-text ml-1 pl-1 pt-1 col-xl-8 col-7">{{ item.seller }}</p>
							</div>
							<div class="rounded crop_image p-0"style="width:100%; overflow:hidden;" >
								<img class="card-img-top d_image "src="{{ item.displayPhoto.url }}" alt="Image Not Found" >
							</div>
							<div id="textholder row" class="m-1 p-1 justify-text-left col" >
								<h5 id="info-h" class="card-text m-0 col-10 p-0" >{{ item.name }}</h5>
								<p id="info-t" class="card-text col-10 p-0">HK${{ item.price }}</p>
							</div>
						</div>
					</a>
				</div >
			{% endfor %}
		</div>

</div>
{% endblock %}

{% block script %}
<script>
var resize = function(){
	//resize the display block and fit with the screen
	$('.crop_image').css({
	'height': $('.crop_image').width()
	});
	ch = $('.crop_image').height();
	cw = $('.crop_image').width();
	console.log(ch, cw);
}

var zoom = function(){
	//zoom the display photo and fit with the display block
	$('.d_image').each(function(){
		current =$(this)
		var ih = current.height();
		var iw = current.width();

		if (iw > ih){
			current.css({'height':ch,'width':'auto'});

			//current.css('margin-top', m);
		}
		if ( ih > iw ){
			current.css({'height':'auto','width':cw});
		}
	});
}

var positioning = function(){
	//center the display photo
	$('.d_image').each(function(){
		current =$(this)
		var ih = current.height();
		var iw = current.width();

		if (iw > ih){
			r = (iw - cw)/ 2;
			current.css({ 'position':'relative','right':r});
			//current.css('margin-top', m);
		}
		if ( ih > iw ){
			t = (ch-ih)/2;
			current.css({'position':'relative','top':t});
		}
	});
}


$(function(){
	//do the functions once when page is loaded
	resize();
	zoom();
	positioning();

	console.log(ch, cw);


	$(window).resize(function() {
		//do functions again when window size change is detected 
		resize();
		zoom();
		positioning();

	});
});

</script>
{% endblock %}